sudo: false
language: rust
rust:
- nightly
- beta
- stable
os:
  - linux
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    - master
addons:
  apt:
    packages:
      - libasound2-dev
matrix:
  allow_failures:
  - rust: nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test -- --all
cache: cargo
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
