[package]
name = "amethyst-rhusics"
version = "0.1.0"
authors = []

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "develop" }
rhusics = { path = "../rhusics/", features = ["ecs"] }
genmesh = "0.5"
rand = "0.3"
